FROM directus/directus:latest

USER root

RUN apk update
RUN apk add sendmail

ENV HOST="0.0.0.0"
ARG PUBLIC_URL
ENV PUBLIC_URL=$PUBLIC_URL
ARG KEY
ENV KEY=$KEY
ARG SECRET
ENV SECRET=$SECRET


ARG ADMIN_EMAIL
ENV ADMIN_EMAIL=$ADMIN_EMAIL
ARG ADMIN_PASSWORD
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD


ENV DB_CLIENT="pg"
ARG DB_HOST
ENV DB_HOST=$DB_HOST
ENV DB_PORT="5432"
ARG DB_DATABASE
ENV DB_DATABASE=$DB_DATABASE
ARG DB_USER
ENV DB_USER=$DB_USER
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD


ARG REDIS
ENV REDIS=$REDIS
ARG REDIS_HOST
ENV REDIS_HOST=$REDIS_HOST
ARG REDIS_PORT
ENV REDIS_PORT=$REDIS_PORT
ARG REDIS_USERNAME
ENV REDIS_USERNAME=$REDIS_USERNAME
ARG REDIS_PASSWORD
ENV REDIS_PASSWORD=$REDIS_PASSWORD


ENV STORAGE_LOCATIONS="s3"
ARG STORAGE_S3_DRIVER
ENV STORAGE_S3_DRIVER=$STORAGE_S3_DRIVER
ARG STORAGE_S3_ROOT
ENV STORAGE_S3_ROOT=$STORAGE_S3_ROOT
ARG STORAGE_S3_KEY
ENV STORAGE_S3_KEY=$STORAGE_S3_KEY
ARG STORAGE_S3_SECRET
ENV STORAGE_S3_SECRET=$STORAGE_S3_SECRET
ARG STORAGE_S3_BUCKET
ENV STORAGE_S3_BUCKET=$STORAGE_S3_BUCKET
ARG STORAGE_S3_REGION
ENV STORAGE_S3_REGION=$STORAGE_S3_REGION
ARG STORAGE_S3_ENDPOINT
ENV STORAGE_S3_ENDPOINT=$STORAGE_S3_ENDPOINT
ARG STORAGE_S3_ACL
ENV STORAGE_S3_ACL=$STORAGE_S3_ACL
ARG STORAGE_S3_SERVER_SIDE_ENCRYPTION
ENV STORAGE_S3_SERVER_SIDE_ENCRYPTION=$STORAGE_S3_SERVER_SIDE_ENCRYPTION

EXPOSE 8055
