FROM directus/directus:latest

ENV HOST="0.0.0.0"
ARG PUBLIC_URL
ENV PUBLIC_URL=$PUBLIC_URL
ARG KEY
ENV KEY=$KEY
ARG SECRET
ENV SECRET=$SECRET
ARG ADMIN_EMAIL
ENV ADMIN_EMAIL=$ADMIN_EMAIL
ARG ADMIN_PASSWORD
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD


ENV DB_CLIENT="pg"
ARG DB_CONNECTION_STRING
ENV DB_CONNECTION_STRING=$DB_CONNECTION_STRING


ARG REDIS
ENV REDIS=$REDIS


ENV STORAGE_LOCATIONS="s3"
ENV STORAGE_S3_DRIVER="s3"
ARG STORAGE_S3_ROOT
ENV STORAGE_S3_ROOT=$STORAGE_S3_ROOT
ARG STORAGE_S3_KEY
ENV STORAGE_S3_KEY=$STORAGE_S3_KEY
ARG STORAGE_S3_SECRET
ENV STORAGE_S3_SECRET=$STORAGE_S3_SECRET
ARG STORAGE_S3_BUCKET
ENV STORAGE_S3_BUCKET=$STORAGE_S3_BUCKET
ARG STORAGE_S3_REGION
ENV STORAGE_S3_REGION=$STORAGE_S3_REGION
ARG STORAGE_S3_ENDPOINT
ENV STORAGE_S3_ENDPOINT=$STORAGE_S3_ENDPOINT
ARG STORAGE_S3_ACL
ENV STORAGE_S3_ACL=$STORAGE_S3_ACL
ARG STORAGE_S3_SERVER_SIDE_ENCRYPTION
ENV STORAGE_S3_SERVER_SIDE_ENCRYPTION=$STORAGE_S3_SERVER_SIDE_ENCRYPTION

EXPOSE 8055
